topic_list:
  - name: arm
    ns: controller
    group: 0
    joints: [ma2010_joint_1_s, ma2010_joint_2_l, ma2010_joint_3_u, ma2010_joint_4_r, ma2010_joint_5_b, ma2010_joint_6_t]
  - name: positioner
    ns: controller
    group: 1
    joints: [d500_joint_1, d500_joint_2]
